# Generated by Django 5.1.3 on 2024-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
