# Generated by Django 5.1.3 on 2024-12-03 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_gallery_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dish_description', models.TextField(blank=True, null=True)),
                ('dish_menu_type', models.CharField(choices=[('emporter', 'Menu à Emporter'), ('ensalle', 'Menu en Salle')], default='ensalle', max_length=20)),
                ('dish_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.dishcategory')),
            ],
        ),
    ]
