# Generated by Django 5.1.3 on 2024-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dishcategory_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_images',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
