# Generated by Django 5.1.3 on 2024-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_categorychoices_remove_dishes_dish_menu_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcategory',
            name='category_menu_type',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='category_menu_type',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_menu_type',
            field=models.CharField(choices=[('emporter', 'Menu à Emporter'), ('ensalle', 'Menu en Salle')], default='ensalle', max_length=20),
        ),
        migrations.DeleteModel(
            name='CategoryChoices',
        ),
    ]
