# Generated by Django 5.1.3 on 2024-12-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_dishcategory_table_alter_dishes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'catégorie de plat du menu En salle'},
        ),
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'plat du menu En salle'},
        ),
        migrations.AlterModelTable(
            name='dishcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dishes',
            table=None,
        ),
    ]
