# Generated by Django 5.1.3 on 2024-12-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_dishcategory_options_alter_dishes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategoryEmporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'catégorie de plat du menu a(Emporter)',
            },
        ),
        migrations.CreateModel(
            name='DishesAEmporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dish_description', models.TextField(blank=True, null=True)),
                ('dish_images', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('dish_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.dishcategoryemporter')),
            ],
            options={
                'verbose_name': 'plat du menu menu a (Emporter)',
            },
        ),
    ]
