# Generated by Django 5.1.3 on 2024-12-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_mysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysetting',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
