# Generated by Django 5.1.3 on 2024-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_mysetting_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(default=3)),
                ('Review_person_img', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
