# Generated by Django 5.1.3 on 2024-12-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title',
            new_name='review_owner',
        ),
    ]
