# Generated by Django 5.1.3 on 2024-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_rename_title_reviews_review_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppeningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('from1', models.CharField(blank=True, max_length=100, null=True)),
                ('to1', models.CharField(blank=True, max_length=100, null=True)),
                ('from2', models.CharField(blank=True, max_length=100, null=True)),
                ('to2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
