# Generated by Django 5.1.3 on 2024-12-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_oppeningday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oppeningday',
            name='closed',
        ),
        migrations.AddField(
            model_name='oppeningday',
            name='oppened',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
